CSV/Models/ErrorViewModel.cs
using System;

namespace CSV.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSV/Models/FileUpload.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSP.Models
{
    public class FileUpload
    {
        public IFormFile files { get; set; }
    }
}

CSV/Models/InvalidRecord.cs
using CSV.Models;
using System.Collections.Generic;

namespace CSP.Models
{
    //creating record list to be accessible globally, used to store invalid records and called in controller. 
    public static class InvalidRecord
    {
        public static List<Record> invalidRecords;

    }
}

CSV/Models/Record.cs
using CsvHelper.Configuration.Attributes;

namespace CSV.Models
{
    public class Record
    {
        [Name(Constants.CsvHeaders.Reference)]
        public int Reference { get; set; }

        [Name(Constants.CsvHeaders.AccountNumber)]
        public string AccountNumber { get; set; }

        [Name(Constants.CsvHeaders.Description)]
        public string Description { get; set; }

        [Name(Constants.CsvHeaders.StartBalance)]
        public double StartBalance { get; set; }

        [Name(Constants.CsvHeaders.Mutation)]
        public double Mutation { get; set; }

        [Name(Constants.CsvHeaders.EndBalance)]
        public double EndBalance { get; set; }

        [Optional]
        public bool? IsValid { get; set; }

        [Optional]
        public string Note { get; set; }
    }
}

CSV/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using CSP.Models;
using CSV.Models;
using CSV.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CSV.Controllers
{
    public class RecordController : Controller
    {
        [HttpGet]
        public IActionResult Index(List<Record> records = null)
        {
            records = records == null ? new List<Record>() : records;

            return View(records);
        }

        [HttpPost]
        public IActionResult Index(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            if (file == null)
            {
                ViewBag.Message = "Please select a XML or CSV file";

                return View();
            }

            string fileName = $"{hostingEnvironment.WebRootPath}/files/{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
            }
            var _recordService = new RecordService();
            var records = _recordService.GetRecordList(file.FileName);
            return Index(records);
        }

        public IActionResult Export()
        {
            ExportInvalidRecords(InvalidRecord.invalidRecords);
            return RedirectToAction("Index");
        }       

        private void ExportInvalidRecords(List<Record> records)
        {
            var _recordService = new RecordService();
            var path = $"{Directory.GetCurrentDirectory()}{@"/wwwroot/files"}" + "/" + "invalid-records.csv";
        
            _recordService.WriteNewFile(path, records);
        }

        private String GetRecordClass(Record record)
        {
            if (record.IsValid == false) return "invalid_row";
            return "";
        }

    }
}

CSV/Views/Record/Index.cshtml
@{
    ViewData["Title"] = "Acme Inc";
    @model IEnumerable<Record>
}

    <div class="text-center">
        <h1 class="display-4">Customer Statement Processor </h1>

        <form asp-controller="Record" asp-action="Index" method="post" enctype="multipart/form-data" autocomplete="off">
            <input type="file" class="input_file" name="file" id="file" accept=".csv, .xml" />
            <hr />
            <button id="upload_btn" type="submit">Upload</button>
        </form>

        @if (Model.Count() > 0)
        {
            <hr />
            <div class="container">
                <table class="record-table">
                    <thead>
                        <tr>
                            <td>Reference</td>
                            <td>Account Number</td>
                            <td>Description</td>
                            <td>Start Balance</td>
                            <td>Mutation</td>
                            <td>End Balance</td>
                            <td>Note</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Record record in Model.OrderByDescending(i => i.IsValid))
                        {
                            <tr id="records" class="@(@record.IsValid == false ? "invalid_row" : "")">
                                <td>@record.Reference</td>
                                <td>@record.AccountNumber</td>
                                <td>@record.Description</td>
                                <td>@record.StartBalance</td>
                                <td>@record.Mutation</td>
                                <td>@record.EndBalance</td>
                                <td>@record.Note</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <hr />
            <!--temporarily disabled until solution is found-->
            <!--<input type="button" id="export_btn" value="Export" title="Export" onclick="location.href='@Url.Action("Export")'" />-->
        }
    </div>

CSV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Record" asp-action="Index">CSP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Acme Inc - CSP <a asp-area="" asp-controller="Home"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>